# This is a basic workflow to help you get started with Actions

name: update

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: "30 0 * * 1"
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
      
      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wget pyyaml ruamel.yaml

      # Runs a set of commands using the runners shell
      - name: update profile
        run: |
          cd confTOyuml
          python donload.py
      - name: commit
        run: |
          git config --global user.email "zqzess@126.com"
          git config --global user.name "zqzess"
          git add .
          git commit -m "update" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Send Success Message
        if: success()
        run: wget https://sc.ftqq.com/${USER_KEY}.send?text=配置文件更新成功
      - name: Send Failed Message
        if: failure()
        run: wget https://sc.ftqq.com/${USER_KEY}.send?text=配置文件更新出错
        env:
          USER_KEY: ${{ secrets.USER_KEY }}
